redis: &redis
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>/1

development: *redis
test: *redis

# change production url here
production: 
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>/1