DELETE_AFTER: '180'
MAX_EXP_DAYS: '365'
EXP_DAYS: '5'
VAPID_PUBLIC_KEY: 'BBHN5o6gF2qsk4E4Lz0NPJ0F1NmOeKzlcKXBYBYq2-iYnUlIEHusCI_ZDDoh1eAB9k00OMmx3PoxiXjtidXthjM='
VAPID_PRIVATE_KEY: 'XMBiME84w7FXbpyEV1_a9h5IJzGsBxK6Bz0l4dGgA9g='
